version: "3.4"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_URLS=https://+:5001;http://+:5000
#      - ASPNETCORE_HTTPS_PORT=5001
    expose:
      - "5000"
#      - "5001"
#    volumes:
#      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets 
#      - ${HOME}/.aspnet/https:/root/.aspnet/https/  
    container_name: webapi   
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
#      - "443:443"
    links:
      - app
  